apply plugin: 'com.android.application'

android {
    compileSdkVersion 33 // Updated
    // buildToolsVersion "26.0.1" // Removed, AGP will use a suitable version
    defaultConfig {
        applicationId "com.uottawa.thirstycactus.taskcactus"
        minSdkVersion 15 // Keeping this as is for now, can be a separate discussion
        targetSdkVersion 33 // Updated
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner" // Updated to AndroidX
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('androidx.test.espresso:espresso-core:3.5.1', {
        exclude group: 'androidx.annotation', module: 'annotation' // Updated exclude
    })
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.9.0' // Design library replacement
    testImplementation 'junit:junit:4.13.2' // Updated JUnit
}
